"test-manager": 测试管理
'test-manager.summary': 测试摘要
'test-manager.manager': 测试用例
'test-manager.TestPlan': 测试计划
'test-manager.TestExecute': 测试执行
'test-manager.report':  测试管理报表
'test-manager.status':  自定义状态
'test-manager.cycle':  测试循环
'test-manager.autotest':  自动化测试

"platform-reports": "报表"
"platform-reports.testreport": "测试管理报表"
